Section "InputClass"
    Identifier "Synaptics TM3471-010"
    MatchIsTouchpad "on"
    Driver "libinput"
    Option "Tapping" "on"                  # Habilita o "tap to click" (1 dedo para clique esquerdo)
    Option "TappingButtonMap" "lmr"        # Mapeia os toques com 1 dedo para o clique esquerdo, 2 dedos para o direito
    Option "ClickMethod" "buttonareas"
    Option "NaturalScrolling" "true"       # Opção para rolagem natural (opcional)
    Option "DisableWhileTyping" "true"     # Desabilita o touchpad enquanto você digita (opcional)
EndSection

